# language doesn't matter, we're only using phantom.js
language: node_js
node_js:
    - 0.8.16
before_script:
    - npm install
script:
    - make test
notifications:
    irc: "irc.freenode.org#sentry"
