# language doesn't matter, we're only using phantom.js
language: node_js
node_js:
    - "0.10"
before_script:
    - npm install
script:
    - ./node_modules/.bin/grunt build
notifications:
    irc: "irc.freenode.org#sentry"
