# language doesn't matter, we're only using phantom.js
language: node_js
node_js:
    - 0.6
before_script:
    - npm install -g jshint
script:
    - jshint .
    - make test
branches:
    only:
        - develop
notifications:
    irc: "irc.freenode.org#sentry"
